/** @typedef {'ACCUMULATION'|'EXPANSION'|'DISTRIBUTION'|'MANIPULATION'} MarketPhase */
/** @typedef {'NO_TRADE'|'SWING'|'POSITION'} TradingMode */

export const MARKET_PHASE = {
  ACCUMULATION: "ACCUMULATION",
  EXPANSION: "EXPANSION",
  DISTRIBUTION: "DISTRIBUTION",
  MANIPULATION: "MANIPULATION",
};

export const TRADING_MODE = {
  NO_TRADE: "NO_TRADE",
  SWING: "SWING",
  POSITION: "POSITION",
};
